import { Lead, Proposal, FollowUp, User, Settings, PricingPlan, LeadActivity, ScheduledMeeting } from './types';
import { DEFAULT_PROPOSAL_CONTENT } from './utils/defaultProposalContent';

export const initialPricingPlans: PricingPlan[] = [
  {
    id: 'PLAN-001',
    name: 'School Premium with ID',
    code: 'SCH-ID',
    defaultPrice: 150,
    billingCycle: 'Per Student / Year',
    description: 'School ERP + Smart RFID/NFC Student Cards & Instant Gate Synchronization',
    features: [
      'Smart RFID / NFC Contactless Student ID Cards',
      'Instant Turnstile / Gate Reader Hardware Sync',
      'Complete Academic ERP & Timetable',
      'Student & Staff Biometric Attendance',
      'Parent & Student Mobile Apps (Android/iOS)',
      'Live Bus Route GPS Tracking & Automated SMS Alerts',
    ],
    isActive: true,
    isPreset: true,
    minStudents: 100,
    sortOrder: 1,
    createdDate: '2026-01-10',
    updatedDate: '2026-08-27',
  },
  {
    id: 'PLAN-002',
    name: 'School Premium',
    code: 'SCH-PREM',
    defaultPrice: 100,
    billingCycle: 'Per Student / Year',
    description: 'Complete School ERP + Student & Staff Mobile Apps + Attendance + Fees + Academic Reports',
    features: [
      'Complete Academic ERP & Timetable',
      'Student & Staff Biometric Attendance',
      'Fee Management & Online Receipts',
      'Parent & Student Mobile Apps (Android/iOS)',
      'Exam & Continuous Evaluation Gradebook',
      'Instant SMS & App Notifications',
    ],
    isActive: true,
    isPreset: true,
    minStudents: 100,
    sortOrder: 2,
    createdDate: '2026-01-10',
    updatedDate: '2026-08-27',
  },
  {
    id: 'PLAN-003',
    name: 'Parent Payment',
    code: 'PARENT-PAY',
    defaultPrice: 200,
    billingCycle: 'Per Student / Year',
    description: 'Parent-oriented communication, digital diaries, direct fee payment gateway & media broadcast',
    features: [
      'Dedicated Parent Portal Mobile App',
      'Integrated Direct Fee Payment Gateway (UPI/Netbanking)',
      'Direct Teacher-Parent Secure Chat',
      'Daily Digital Homework Diary & Announcements',
      'School Event Photo Gallery & Circulars',
    ],
    isActive: true,
    isPreset: true,
    minStudents: 100,
    sortOrder: 3,
    createdDate: '2026-01-10',
    updatedDate: '2026-08-27',
  },
  {
    id: 'PLAN-004',
    name: 'Introduction Trial Price',
    code: 'TRIAL',
    defaultPrice: 45,
    billingCycle: 'Per Student / Term',
    description: '1-Term evaluation pilot package with standard modules for quick onboarding and evaluation',
    features: [
      'Standard ERP & Attendance',
      '1-Term Evaluation Pilot',
      'Basic Cloud Hosting & Backups',
      '48-Hour Rapid Setup',
      'Email & WhatsApp Support',
    ],
    isActive: true,
    isPreset: false,
    minStudents: 100,
    sortOrder: 4,
    createdDate: '2026-01-10',
    updatedDate: '2026-08-27',
  },
  {
    id: 'PLAN-005',
    name: 'Special Price',
    code: 'SPECIAL-VOL',
    defaultPrice: 75,
    billingCycle: 'Per Student / Year',
    description: 'Custom institutional discount package for group institutions, trusts, or high-volume schools',
    features: [
      'Multi-Campus Centralized Management Dashboard',
      'Dedicated Key Account Manager & Technical Lead',
      'Custom ERP Report Builders & Data Export APIs',
      'Priority 99.9% Cloud Uptime SLA Guarantee',
      'Subsidized Additional Smart RFID Hardware',
    ],
    isActive: true,
    isPreset: false,
    minStudents: 500,
    sortOrder: 5,
    createdDate: '2026-01-10',
    updatedDate: '2026-08-27',
  },
];

export const initialSettings: Settings = {
  companyName: 'Casbiro Solutions Private Limited',
  brandName: 'MYSAR ERP',
  tagline: 'My Student Analysis Record (MYSAR) - Transforming Education Through Smart Digital Solutions',
  address: 'No. 4/461, 2nd Floor, Valamkattil Tower, Judgemukku, Kakkanad, Kochi, Kerala – 682021',
  phone: '+91 7994 807 907 / +91 7994 806 906 / +91 7994 805 905',
  email: 'support@casbiro.com / sales@mysar.in',
  website: 'https://mysar.in',
  gstNumber: '32AABCC8921F1ZX',
  proposalPrefix: 'MYSAR/PROP/2026/',
  proposalSequence: 45,
  driveFolderId: '1AbCdEfGhIjKlMnOpQrStUvWxYz_MYSAR_Proposals',
  gasWebAppUrl: '',
  spreadsheetId: '1MYSAR_LEAD_MANAGEMENT_GOOGLE_SHEET_ID_XXXX',
  currencySymbol: '₹',
  pricingTypes: [
    {
      name: 'Special Offer (School Payment)',
      description: 'Special discounted institutional rate for complete student profile & continuous development (₹75/student/yr)',
      suggestedFeatures: ['Complete Student Digital Record', 'Attendance & Leave Management', 'Fee & Online Collection', 'Report Card & Analytics'],
    },
    {
      name: 'Standard Pricing (Parent Payment)',
      description: 'Parent-subscribed model with mobile app access, OTP login, live diary & notifications (₹150/student/yr)',
      suggestedFeatures: ['Parent & Teacher Mobile Apps', 'Live Homework & Diary', 'Online Fee Payment', 'Real-time Alerts'],
    },
    {
      name: 'Standard Pricing (School Payment)',
      description: 'Full school ERP & teacher dashboard for comprehensive academic monitoring (₹100/student/yr)',
      suggestedFeatures: ['Teacher Dashboard', 'School Administration', 'Exam & Assessment System', 'ID Card & Certification'],
    },
    {
      name: 'Introductory Trial Offer',
      description: '1st Year promotional onboarding package with complete modules & data setup support (₹40/student/yr)',
      suggestedFeatures: ['Full 12 MYSAR Modules', 'Free Data Migration', 'Teacher & Parent Orientation', 'First Year Special Rate'],
    },
  ],
  emailSubjectTemplate: 'MYSAR Proposal for Implementation - {{INSTITUTE_NAME}}',
  emailBodyTemplate: `Dear {{CONTACT_PERSON}},

Greetings from Casbiro Solutions Private Limited.

Thank you for your interest in the MYSAR (My Student Analysis Record) platform for {{INSTITUTE_NAME}}.

Please find attached our official Proposal for Implementation (Ref: {{PROPOSAL_NUMBER}}).

Key Details:
• Institution: {{INSTITUTE_NAME}}
• Student Enrollment: {{STUDENT_COUNT}}
• Pricing Plan: {{PRICING_TYPE}}
• Rate: {{PRICE_PER_STUDENT}} / student / year
• Total Investment: {{TOTAL_AMOUNT}}

Our team provides end-to-end setup, data onboarding, teacher training, and continuous technical support.

Feel free to reach out to us directly for live demonstrations or discussion.

Warm regards,
Team MYSAR | Casbiro Solutions Private Limited
No. 4/461, Valamkattil Tower, Judgemukku, Kakkanad, Kochi, Kerala – 682021
Phone: +91 7994 807 907 / +91 7994 806 906
Email: support@casbiro.com | https://mysar.in`,
  proposalContent: DEFAULT_PROPOSAL_CONTENT,
};

export const initialUsers: User[] = [
  {
    id: 'USR-001',
    userId: 'rafeeh.vk',
    password: 'Password@123',
    name: 'Rafeeh V K',
    email: 'rafeeh.vk@casbiro.com',
    mobile: '+91 98471 23456',
    role: 'Admin',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'USR-002',
    userId: 'sakeer',
    password: 'Password@123',
    name: 'Sakeer Ali V',
    email: 'sakeer@casbiro.com',
    mobile: '+91 98460 00000',
    role: 'Manager',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'USR-003',
    userId: 'anand.k',
    password: 'Password@123',
    name: 'Anand Kumar',
    email: 'anand.k@casbiro.com',
    mobile: '+91 98452 34567',
    role: 'Manager',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'USR-004',
    userId: 'priya.s',
    password: 'Password@123',
    name: 'Priya Sharma',
    email: 'priya.s@casbiro.com',
    mobile: '+91 98453 45678',
    role: 'Salesperson',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'USR-005',
    userId: 'suhail.m',
    password: 'Password@123',
    name: 'Mohammed Suhail',
    email: 'suhail.m@casbiro.com',
    mobile: '+91 98454 56789',
    role: 'Salesperson',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
  },
];

const today = new Date().toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];
const nextWeek = new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0];

export const initialLeads: Lead[] = [
  {
    id: 'LEAD-2026-000',
    leadDate: '2026-04-28',
    instituteName: 'MET English Medium High School',
    contactPerson: 'The Principal / Management',
    mobile: '+91 98460 11223',
    email: 'principal@methighschool.edu.in',
    address: 'Kochi, Kerala',
    studentCount: 850,
    leadSource: 'Direct Visit',
    assignedTo: 'Sakeer Ali V',
    priority: 'High',
    status: 'Proposal Sent',
    followUpDate: today,
    remarks: 'Official Proposal for Implementation submitted. Follow up on management board review.',
    createdBy: 'Sakeer Ali V',
    createdDate: '2026-04-28',
    updatedDate: '2026-08-27',
  },
  {
    id: 'LEAD-2026-001',
    leadDate: '2026-08-10',
    instituteName: 'Greenwood International Public School',
    contactPerson: 'Dr. Ramesh Narayan (Principal)',
    mobile: '+91 98450 88776',
    email: 'principal@greenwoodschool.edu.in',
    address: 'Sarjapur Main Road, Bangalore, Karnataka - 560035',
    studentCount: 850,
    leadSource: 'Referral',
    assignedTo: 'Anand Kumar',
    priority: 'High',
    status: 'Send Proposal',
    followUpDate: today,
    remarks: 'Principal requested commercial quote after successful product demo yesterday. Highly interested in RFID Attendance and Parent App.',
    createdBy: 'Anand Kumar',
    createdDate: '2026-08-10',
    updatedDate: '2026-08-26',
  },
  {
    id: 'LEAD-2026-002',
    leadDate: '2026-08-12',
    instituteName: 'St. Mary Higher Secondary Academy',
    contactPerson: 'Fr. George Matthew (Director)',
    mobile: '+91 98451 77665',
    email: 'director@stmaryacademy.org',
    address: 'Residency Road, Richmond Town, Bangalore, Karnataka - 560025',
    studentCount: 1200,
    leadSource: 'Exhibition',
    assignedTo: 'Priya Sharma',
    priority: 'High',
    status: 'Qualified',
    followUpDate: today,
    remarks: 'Management committee looking to replace legacy ERP before term 2. Demo scheduled for Friday morning.',
    createdBy: 'Priya Sharma',
    createdDate: '2026-08-12',
    updatedDate: '2026-08-25',
  },
  {
    id: 'LEAD-2026-003',
    leadDate: '2026-08-15',
    instituteName: 'Vidya Mandir PU & Degree College',
    contactPerson: 'Prof. S. K. Kulkarni (Administrator)',
    mobile: '+91 98452 66554',
    email: 'admin@vidyamandir.ac.in',
    address: 'Malleswaram 18th Cross, Bangalore, Karnataka - 560003',
    studentCount: 650,
    leadSource: 'Website',
    assignedTo: 'Mohammed Suhail',
    priority: 'Medium',
    status: 'Proposal Sent',
    followUpDate: tomorrow,
    remarks: 'Sent Proposal MYSAR/PROP/2026/039 for Special Price @ ₹70/student. Decision expected by end of week.',
    createdBy: 'Mohammed Suhail',
    createdDate: '2026-08-15',
    updatedDate: '2026-08-24',
  },
  {
    id: 'LEAD-2026-004',
    leadDate: '2026-08-18',
    instituteName: 'Oakridge Global Cambridge Academy',
    contactPerson: 'Mrs. Anita Deshmukh (Vice Principal)',
    mobile: '+91 98453 55443',
    email: 'anita.d@oakridgeglobal.org',
    address: 'Whitefield Main Road, Bangalore, Karnataka - 560066',
    studentCount: 500,
    leadSource: 'Field Visit',
    assignedTo: 'Anand Kumar',
    priority: 'High',
    status: 'Won',
    followUpDate: '2026-09-01',
    remarks: 'Contract signed for 500 students @ ₹75/student (Special Price). Implementation kickoff scheduled.',
    createdBy: 'Anand Kumar',
    createdDate: '2026-08-18',
    updatedDate: '2026-08-26',
  },
  {
    id: 'LEAD-2026-005',
    leadDate: '2026-08-20',
    instituteName: 'Silver Oaks High School',
    contactPerson: 'Mr. Rajesh Hegde (Chairman)',
    mobile: '+91 98454 44332',
    email: 'trustee@silveroaks.edu',
    address: 'Koramangala 4th Block, Bangalore, Karnataka - 560034',
    studentCount: 920,
    leadSource: 'Cold Call',
    assignedTo: 'Priya Sharma',
    priority: 'Medium',
    status: 'Negotiation',
    followUpDate: today,
    remarks: 'Negotiating ID card integration pricing. Willing to close at ₹85 with Smart ID cards.',
    createdBy: 'Priya Sharma',
    createdDate: '2026-08-20',
    updatedDate: '2026-08-26',
  },
  {
    id: 'LEAD-2026-006',
    leadDate: '2026-08-22',
    instituteName: 'National Hill View Public School',
    contactPerson: 'Dr. Meera Chandrashekar (Principal)',
    mobile: '+91 98455 33221',
    email: 'principal@nhvps.ac.in',
    address: 'Banashankari 3rd Stage, Bangalore, Karnataka - 560085',
    studentCount: 1100,
    leadSource: 'Referral',
    assignedTo: 'Mohammed Suhail',
    priority: 'High',
    status: 'New',
    followUpDate: today,
    remarks: 'New inbound lead from direct referral of Greenwood School. Interested in complete demo.',
    createdBy: 'Mohammed Suhail',
    createdDate: '2026-08-22',
    updatedDate: '2026-08-22',
  },
  {
    id: 'LEAD-2026-007',
    leadDate: '2026-08-23',
    instituteName: 'Delhi Public Academy, North Campus',
    contactPerson: 'Mr. Arvind Saxena (IT Head)',
    mobile: '+91 98456 22110',
    email: 'ithead@dpnorth.org',
    address: 'Bellary Road, Yelahanka, Bangalore, Karnataka - 560064',
    studentCount: 1450,
    leadSource: 'Social Media',
    assignedTo: 'Anand Kumar',
    priority: 'Medium',
    status: 'Demo Scheduled',
    followUpDate: tomorrow,
    remarks: 'Online zoom demo scheduled with IT and admin team for Friday 3 PM.',
    createdBy: 'Anand Kumar',
    createdDate: '2026-08-23',
    updatedDate: '2026-08-25',
  },
  {
    id: 'LEAD-2026-008',
    leadDate: '2026-08-24',
    instituteName: 'Apex Oxford Matriculation School',
    contactPerson: 'Mr. V. Sundaram (Secretary)',
    mobile: '+91 98457 11009',
    email: 'admin@apexoxford.edu.in',
    address: 'Hosur Main Road, Bommanahalli, Bangalore, Karnataka - 560068',
    studentCount: 420,
    leadSource: 'Field Visit',
    assignedTo: 'Priya Sharma',
    priority: 'Low',
    status: 'Contacted',
    followUpDate: nextWeek,
    remarks: 'Met secretary, left product brochure. Follow-up after school board meeting next Monday.',
    createdBy: 'Priya Sharma',
    createdDate: '2026-08-24',
    updatedDate: '2026-08-24',
  },
  {
    id: 'LEAD-2026-009',
    leadDate: '2026-08-01',
    instituteName: 'Sunrise Montessori & Primary School',
    contactPerson: 'Mrs. Kavitha Rao (Founder)',
    mobile: '+91 98458 00998',
    email: 'kavitha@sunrisemontessori.org',
    address: 'Indiranagar 100ft Road, Bangalore, Karnataka - 560038',
    studentCount: 180,
    leadSource: 'Website',
    assignedTo: 'Mohammed Suhail',
    priority: 'Low',
    status: 'Lost',
    followUpDate: '2026-08-15',
    remarks: 'Budget constraints for current academic year. May reconsider next year.',
    createdBy: 'Mohammed Suhail',
    createdDate: '2026-08-01',
    updatedDate: '2026-08-15',
  },
];

export const initialProposals: Proposal[] = [
  {
    id: 'PROP-2026-000',
    leadId: 'LEAD-2026-000',
    proposalNumber: 'MYSAR/PROP/2026/044',
    proposalDate: '2026-04-28',
    instituteName: 'MET English Medium High School',
    contactPerson: 'The Principal / Management',
    leadEmail: 'principal@methighschool.edu.in',
    studentCount: 850,
    pricingType: 'Special Offer (School Payment)',
    pricePerStudent: 75,
    totalAmount: 63750,
    pricingItems: [
      {
        id: 'prop-0-item-1',
        pricingType: 'Special Offer (School Payment)',
        pricePerStudent: 75,
        studentCount: 850,
        totalAmount: 63750,
        description: 'Special Price for MET English Medium High School - All 12 MYSAR modules included',
        isPrimary: true,
      },
      {
        id: 'prop-0-item-2',
        pricingType: 'Introductory Trial Offer',
        pricePerStudent: 40,
        studentCount: 850,
        totalAmount: 34000,
        description: 'Introductory Trial Price (Applicable for the first year only)',
        isPrimary: false,
      },
      {
        id: 'prop-0-item-3',
        pricingType: 'Standard Pricing (Parent Payment)',
        pricePerStudent: 150,
        studentCount: 850,
        totalAmount: 127500,
        description: 'Standard parent payment model with mobile apps and OTP login',
        isPrimary: false,
      },
    ],
    proposalStatus: 'Sent',
    createdBy: 'Sakeer Ali V',
    createdDate: '2026-04-28',
    sentDate: '2026-04-28',
    validUntil: '2026-09-30',
    notes: 'Official 14-page Proposal for Implementation submitted.',
  },
  {
    id: 'PROP-2026-001',
    leadId: 'LEAD-2026-004',
    proposalNumber: 'MYSAR/PROP/2026/040',
    proposalDate: '2026-08-19',
    instituteName: 'Oakridge Global Cambridge Academy',
    contactPerson: 'Mrs. Anita Deshmukh (Vice Principal)',
    studentCount: 500,
    pricingType: 'Special Price',
    pricePerStudent: 75,
    totalAmount: 37500,
    pricingItems: [
      {
        id: 'prop-1-item-1',
        pricingType: 'Special Price',
        pricePerStudent: 75,
        studentCount: 500,
        totalAmount: 37500,
        description: 'Complete ERP + Mobile Apps + Automated Attendance with Volume Rebate',
        isPrimary: true,
      },
      {
        id: 'prop-1-item-2',
        pricingType: 'School Premium with ID',
        pricePerStudent: 95,
        studentCount: 500,
        totalAmount: 47500,
        description: 'Includes Smart RFID/NFC Student Cards & Instant Gate Synchronization',
        isPrimary: false,
      },
    ],
    proposalStatus: 'Approved',
    createdBy: 'Anand Kumar',
    createdDate: '2026-08-19',
    sentDate: '2026-08-19',
    validUntil: '2026-09-19',
    notes: 'Approved by board. Signed agreement received.',
  },
  {
    id: 'PROP-2026-002',
    leadId: 'LEAD-2026-003',
    proposalNumber: 'MYSAR/PROP/2026/039',
    proposalDate: '2026-08-20',
    instituteName: 'Vidya Mandir PU & Degree College',
    contactPerson: 'Prof. S. K. Kulkarni (Administrator)',
    studentCount: 650,
    pricingType: 'Special Price',
    pricePerStudent: 70,
    totalAmount: 45500,
    pricingItems: [
      {
        id: 'prop-2-item-1',
        pricingType: 'Special Price',
        pricePerStudent: 70,
        studentCount: 650,
        totalAmount: 45500,
        description: 'Institutional discount package with priority cloud hosting & exam analytics',
        isPrimary: true,
      },
      {
        id: 'prop-2-item-2',
        pricingType: 'Introduction Trial Price',
        pricePerStudent: 45,
        studentCount: 650,
        totalAmount: 29250,
        description: '1-Term pilot package for evaluation',
        isPrimary: false,
      },
      {
        id: 'prop-2-item-3',
        pricingType: 'School Premium with ID',
        pricePerStudent: 90,
        studentCount: 650,
        totalAmount: 58500,
        description: 'Full ERP + Biometric Smart RFID Cards sync',
        isPrimary: false,
      },
    ],
    proposalStatus: 'Sent',
    createdBy: 'Mohammed Suhail',
    createdDate: '2026-08-20',
    sentDate: '2026-08-20',
    validUntil: '2026-09-20',
    notes: 'Proposal delivered by email and hand copy to administrative director.',
  },
  {
    id: 'PROP-2026-003',
    leadId: 'LEAD-2026-005',
    proposalNumber: 'MYSAR/PROP/2026/041',
    proposalDate: '2026-08-22',
    instituteName: 'Silver Oaks High School',
    contactPerson: 'Mr. Rajesh Hegde (Chairman)',
    studentCount: 920,
    pricingType: 'School Premium with ID',
    pricePerStudent: 95,
    totalAmount: 87400,
    pricingItems: [
      {
        id: 'prop-3-item-1',
        pricingType: 'School Premium with ID',
        pricePerStudent: 95,
        studentCount: 920,
        totalAmount: 87400,
        description: 'Complete ERP + Parent Mobile Apps + Smart RFID Cards & Readers',
        isPrimary: true,
      },
      {
        id: 'prop-3-item-2',
        pricingType: 'School Premium',
        pricePerStudent: 80,
        studentCount: 920,
        totalAmount: 73600,
        description: 'Complete ERP + Mobile Apps without physical RFID cards',
        isPrimary: false,
      },
    ],
    proposalStatus: 'Negotiating',
    createdBy: 'Priya Sharma',
    createdDate: '2026-08-22',
    sentDate: '2026-08-22',
    validUntil: '2026-09-22',
    notes: 'Negotiating custom card design and batch printing fees.',
  },
];

export const initialFollowUps: FollowUp[] = [
  {
    id: 'FUP-2026-001',
    leadId: 'LEAD-2026-001',
    instituteName: 'Greenwood International Public School',
    followUpDate: today,
    staff: 'Anand Kumar',
    followUpType: 'Demo',
    discussion: 'Demonstrated parent notification module and RFID reader sync to Dr. Ramesh and 3 coordinators.',
    nextFollowUpDate: today,
    status: 'Completed',
    remarks: 'Client requested formal commercial proposal immediately.',
    createdDate: yesterday,
  },
  {
    id: 'FUP-2026-002',
    leadId: 'LEAD-2026-002',
    instituteName: 'St. Mary Higher Secondary Academy',
    followUpDate: today,
    staff: 'Priya Sharma',
    followUpType: 'Meeting',
    discussion: 'Review existing student database and ERP migration requirements.',
    nextFollowUpDate: today,
    status: 'Pending',
    remarks: 'Prepare migration timeline slide.',
    createdDate: yesterday,
  },
  {
    id: 'FUP-2026-003',
    leadId: 'LEAD-2026-005',
    instituteName: 'Silver Oaks High School',
    followUpDate: today,
    staff: 'Priya Sharma',
    followUpType: 'Call',
    discussion: 'Price negotiation call with Chairman regarding smart ID card hardware costs.',
    nextFollowUpDate: tomorrow,
    status: 'Pending',
    remarks: 'Offer 5% discount on ID hardware if 2-year contract is committed.',
    createdDate: yesterday,
  },
  {
    id: 'FUP-2026-004',
    leadId: 'LEAD-2026-006',
    instituteName: 'National Hill View Public School',
    followUpDate: today,
    staff: 'Mohammed Suhail',
    followUpType: 'Call',
    discussion: 'Initial qualification call with Dr. Meera Chandrashekar.',
    nextFollowUpDate: tomorrow,
    status: 'Pending',
    remarks: 'Understand current attendance and SMS notification workflow.',
    createdDate: today,
  },
  {
    id: 'FUP-2026-005',
    leadId: 'LEAD-2026-007',
    instituteName: 'Delhi Public Academy, North Campus',
    followUpDate: tomorrow,
    staff: 'Anand Kumar',
    followUpType: 'Demo',
    discussion: 'Full online walkthrough for 1450 students configuration.',
    nextFollowUpDate: nextWeek,
    status: 'Pending',
    remarks: 'Send Zoom invite 30 minutes prior.',
    createdDate: '2026-08-25',
  },
];

export const initialActivities: LeadActivity[] = [
  // LEAD-2026-000 (MET English Medium High School)
  {
    id: 'ACT-2026-001',
    leadId: 'LEAD-2026-000',
    type: 'system',
    title: 'Lead Created',
    description: 'New institutional lead registered via Direct Visit by Sakeer Ali V for 850 students.',
    actor: 'Sakeer Ali V',
    actorRole: 'Admin',
    timestamp: '2026-04-28 09:30:00',
    metadata: {
      field: 'status',
      newValue: 'New',
    },
  },
  {
    id: 'ACT-2026-002',
    leadId: 'LEAD-2026-000',
    type: 'followup',
    title: 'Site Visit & Meeting Completed',
    description: 'Conducted in-person meeting with School Management & Principal to present MYSAR academic features.',
    actor: 'Sakeer Ali V',
    actorRole: 'Admin',
    timestamp: '2026-04-28 11:15:00',
    metadata: {
      followUpType: 'Site Visit',
      statusBadge: 'Completed',
    },
  },
  {
    id: 'ACT-2026-003',
    leadId: 'LEAD-2026-000',
    type: 'proposal',
    title: 'Implementation Proposal Generated',
    description: 'Generated official 14-page Proposal MYSAR/PROP/2026/044 for 850 students @ ₹75/student/yr (₹63,750).',
    actor: 'Sakeer Ali V',
    actorRole: 'Admin',
    timestamp: '2026-04-28 14:00:00',
    metadata: {
      proposalNumber: 'MYSAR/PROP/2026/044',
      proposalAmount: 63750,
      statusBadge: 'Sent',
    },
  },
  {
    id: 'ACT-2026-004',
    leadId: 'LEAD-2026-000',
    type: 'email',
    title: 'Official Proposal Dispatched via Email',
    description: 'Sent proposal package with fee comparison and module roadmap to principal@methighschool.edu.in.',
    actor: 'Sakeer Ali V',
    actorRole: 'Admin',
    timestamp: '2026-04-28 14:30:00',
    metadata: {
      emailTo: 'principal@methighschool.edu.in',
      emailSubject: 'MYSAR Proposal for Implementation - MET English Medium High School',
      statusBadge: 'Delivered',
    },
  },
  {
    id: 'ACT-2026-005',
    leadId: 'LEAD-2026-000',
    type: 'change',
    title: 'Status Updated to Proposal Sent',
    description: 'Lead status changed from "Contacted" to "Proposal Sent". Priority marked as High.',
    actor: 'Sakeer Ali V',
    actorRole: 'Admin',
    timestamp: '2026-04-28 14:35:00',
    metadata: {
      field: 'status',
      oldValue: 'Contacted',
      newValue: 'Proposal Sent',
    },
  },
  {
    id: 'ACT-2026-006',
    leadId: 'LEAD-2026-000',
    type: 'note',
    title: 'Management Board Review Scheduled',
    description: 'Principal confirmed the proposal will be reviewed in the upcoming executive committee meeting.',
    actor: 'Sakeer Ali V',
    actorRole: 'Admin',
    timestamp: '2026-08-27 16:45:00',
  },

  // LEAD-2026-001 (Greenwood International Public School)
  {
    id: 'ACT-2026-010',
    leadId: 'LEAD-2026-001',
    type: 'system',
    title: 'Lead Created',
    description: 'Registered inbound lead from Website for 1,200 students. Assigned to Anand Kumar.',
    actor: 'Anand Kumar',
    actorRole: 'Salesperson',
    timestamp: '2026-08-10 10:00:00',
    metadata: {
      field: 'status',
      newValue: 'New',
    },
  },
  {
    id: 'ACT-2026-011',
    leadId: 'LEAD-2026-001',
    type: 'followup',
    title: 'Product Demo Completed',
    description: 'Demonstrated parent notification module and RFID reader sync to Dr. Ramesh and 3 coordinators.',
    actor: 'Anand Kumar',
    actorRole: 'Salesperson',
    timestamp: '2026-08-24 15:30:00',
    metadata: {
      followUpType: 'Demo',
      statusBadge: 'Completed',
    },
  },
  {
    id: 'ACT-2026-012',
    leadId: 'LEAD-2026-001',
    type: 'proposal',
    title: 'Proposal Generated',
    description: 'Created proposal MYSAR/PROP/2026/040 for 1,200 students with School Premium with ID @ ₹95/student (₹1,14,000).',
    actor: 'Anand Kumar',
    actorRole: 'Salesperson',
    timestamp: '2026-08-24 17:00:00',
    metadata: {
      proposalNumber: 'MYSAR/PROP/2026/040',
      proposalAmount: 114000,
    },
  },
  {
    id: 'ACT-2026-013',
    leadId: 'LEAD-2026-001',
    type: 'email',
    title: 'Proposal Email Sent',
    description: 'Commercial proposal sent to principal@greenwoodschool.edu.in with custom discount sheet.',
    actor: 'Anand Kumar',
    actorRole: 'Salesperson',
    timestamp: '2026-08-24 17:15:00',
    metadata: {
      emailTo: 'principal@greenwoodschool.edu.in',
      emailSubject: 'MYSAR Proposal - Greenwood International Public School',
    },
  },
  {
    id: 'ACT-2026-014',
    leadId: 'LEAD-2026-001',
    type: 'change',
    title: 'Status Updated to Proposal Sent',
    description: 'Status progressed from "Demo Completed" to "Proposal Sent".',
    actor: 'Anand Kumar',
    actorRole: 'Salesperson',
    timestamp: '2026-08-24 17:20:00',
    metadata: {
      field: 'status',
      oldValue: 'Demo Completed',
      newValue: 'Proposal Sent',
    },
  },

  // LEAD-2026-002 (St. Mary Higher Secondary Academy)
  {
    id: 'ACT-2026-020',
    leadId: 'LEAD-2026-002',
    type: 'system',
    title: 'Lead Created',
    description: 'Referral lead entered by Priya Sharma for 780 students.',
    actor: 'Priya Sharma',
    actorRole: 'Salesperson',
    timestamp: '2026-08-12 11:00:00',
  },
  {
    id: 'ACT-2026-021',
    leadId: 'LEAD-2026-002',
    type: 'followup',
    title: 'Requirement Gathering Meeting',
    description: 'Review existing student database and ERP migration requirements with Sister Maria.',
    actor: 'Priya Sharma',
    actorRole: 'Salesperson',
    timestamp: '2026-08-25 14:00:00',
    metadata: {
      followUpType: 'Meeting',
      statusBadge: 'Completed',
    },
  },
  {
    id: 'ACT-2026-022',
    leadId: 'LEAD-2026-002',
    type: 'email',
    title: 'Meeting Summary & Brochure Dispatched',
    description: 'Sent MYSAR overview brochure and migration roadmap to stmaryschool@gmail.com.',
    actor: 'Priya Sharma',
    actorRole: 'Salesperson',
    timestamp: '2026-08-25 16:30:00',
    metadata: {
      emailTo: 'stmaryschool@gmail.com',
      emailSubject: 'MYSAR Implementation & Data Migration Guide - St. Mary Academy',
    },
  },
  {
    id: 'ACT-2026-023',
    leadId: 'LEAD-2026-002',
    type: 'change',
    title: 'Lead Status Changed to Qualified',
    description: 'Lead status updated from "Contacted" to "Qualified". High priority set.',
    actor: 'Priya Sharma',
    actorRole: 'Salesperson',
    timestamp: '2026-08-25 16:45:00',
    metadata: {
      field: 'status',
      oldValue: 'Contacted',
      newValue: 'Qualified',
    },
  },

  // LEAD-2026-004 (Oakridge Global Academy)
  {
    id: 'ACT-2026-030',
    leadId: 'LEAD-2026-004',
    type: 'system',
    title: 'Lead Created',
    description: 'Field visit lead entered by Anand Kumar for 500 students.',
    actor: 'Anand Kumar',
    actorRole: 'Salesperson',
    timestamp: '2026-08-18 10:00:00',
  },
  {
    id: 'ACT-2026-031',
    leadId: 'LEAD-2026-004',
    type: 'followup',
    title: 'On-site Commercial Discussion',
    description: 'Finalized annual pricing and student batch sizing with Director Mrs. Anita Desai.',
    actor: 'Anand Kumar',
    actorRole: 'Salesperson',
    timestamp: '2026-08-22 11:30:00',
    metadata: {
      followUpType: 'Meeting',
    },
  },
  {
    id: 'ACT-2026-032',
    leadId: 'LEAD-2026-004',
    type: 'proposal',
    title: 'Proposal Approved & Contract Signed',
    description: 'Contract confirmed for 500 students @ ₹75/student. Total Annual Value ₹37,500.',
    actor: 'Anand Kumar',
    actorRole: 'Salesperson',
    timestamp: '2026-08-26 14:00:00',
    metadata: {
      proposalNumber: 'MYSAR/PROP/2026/038',
      proposalAmount: 37500,
      statusBadge: 'Approved',
    },
  },
  {
    id: 'ACT-2026-033',
    leadId: 'LEAD-2026-004',
    type: 'change',
    title: 'Deal Won 🎉',
    description: 'Status changed from "Negotiation" to "Won". Kickoff date confirmed.',
    actor: 'Anand Kumar',
    actorRole: 'Salesperson',
    timestamp: '2026-08-26 14:10:00',
    metadata: {
      field: 'status',
      oldValue: 'Negotiation',
      newValue: 'Won',
    },
  },

  // LEAD-2026-005 (Silver Oaks High School)
  {
    id: 'ACT-2026-040',
    leadId: 'LEAD-2026-005',
    type: 'system',
    title: 'Lead Created',
    description: 'Inbound cold-call lead entered by Priya Sharma for 920 students.',
    actor: 'Priya Sharma',
    actorRole: 'Salesperson',
    timestamp: '2026-08-20 09:30:00',
  },
  {
    id: 'ACT-2026-041',
    leadId: 'LEAD-2026-005',
    type: 'proposal',
    title: 'Proposal Generated',
    description: 'Generated Proposal MYSAR/PROP/2026/041 for 920 students with Smart ID package (₹87,400).',
    actor: 'Priya Sharma',
    actorRole: 'Salesperson',
    timestamp: '2026-08-22 15:00:00',
    metadata: {
      proposalNumber: 'MYSAR/PROP/2026/041',
      proposalAmount: 87400,
    },
  },
  {
    id: 'ACT-2026-042',
    leadId: 'LEAD-2026-005',
    type: 'email',
    title: 'Proposal Dispatched by Email',
    description: 'Email sent to trustee@silveroaks.edu with itemized Smart ID hardware breakdown.',
    actor: 'Priya Sharma',
    actorRole: 'Salesperson',
    timestamp: '2026-08-22 15:20:00',
    metadata: {
      emailTo: 'trustee@silveroaks.edu',
      emailSubject: 'MYSAR Proposal - Silver Oaks High School',
    },
  },
  {
    id: 'ACT-2026-043',
    leadId: 'LEAD-2026-005',
    type: 'change',
    title: 'Status Updated to Negotiation',
    description: 'Status changed from "Proposal Sent" to "Negotiation". Discussing ID card volume discount.',
    actor: 'Priya Sharma',
    actorRole: 'Salesperson',
    timestamp: '2026-08-26 12:00:00',
    metadata: {
      field: 'status',
      oldValue: 'Proposal Sent',
      newValue: 'Negotiation',
    },
  },
];

export const initialScheduledMeetings: ScheduledMeeting[] = [
  {
    id: 'MEET-2026-001',
    title: 'MYSAR ERP & SIS Product Walkthrough',
    leadId: 'LEAD-2026-001',
    instituteName: 'Greenwood Public School',
    contactPerson: 'Dr. Ramesh Sharma',
    participantEmails: ['principal@greenwood.edu.in', 'academic.head@greenwood.edu.in'],
    meetingUri: 'https://meet.google.com/abc-mysar-gwps',
    meetingCode: 'abc-mysar-gwps',
    scheduledDate: '2026-09-02',
    scheduledTime: '11:00',
    durationMinutes: 45,
    agenda: 'Demonstrate attendance automation, biometric integration, and parent mobile application to the academic council.',
    status: 'Scheduled',
    spaceName: 'spaces/abc-mysar-gwps',
    createdDate: '2026-08-28',
    createdBy: 'Rahul Mehta',
  },
  {
    id: 'MEET-2026-002',
    title: 'Smart RFID & Fee Gateway Executive Review',
    leadId: 'LEAD-2026-002',
    instituteName: 'St. Xavier International Academy',
    contactPerson: 'Sister Mary Joseph',
    participantEmails: ['director@stxavier.edu.in', 'accounts@stxavier.edu.in'],
    meetingUri: 'https://meet.google.com/xyz-mysar-stx',
    meetingCode: 'xyz-mysar-stx',
    scheduledDate: '2026-09-03',
    scheduledTime: '15:30',
    durationMinutes: 30,
    agenda: 'Review RFID bus GPS tracking hardware and online fee collection gateway reconciliation.',
    status: 'Scheduled',
    spaceName: 'spaces/xyz-mysar-stx',
    createdDate: '2026-08-29',
    createdBy: 'Priya Sharma',
  },
];


